name = "The Village 26.1"
author = "CracklyDuck"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4754ef082158e89adc27f3b3f112f50639c1f35dfeb6a4e241c46984325bf94"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
