name = "The Village 26.1"
author = "CracklyDuck"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b0d248f44146f36e524a7b54eaf7e29154e0c1e6cb42a27aad7c0a182258b8d"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
