name = "The Village 26.1"
author = "CracklyDuck"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "970b2df7c23f1fef8266c7ee71fdd62ded845dc8f27870063c0039acc5f38dc9"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
