name = "The Village 26.3"
author = "CracklyDuck"
version = "1.26.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6619747b42906f6f11dc57db4aff793778067ae316a7bc00d028ae16858890c5"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
