name = "The Village 26.3"
author = "CracklyDuck"
version = "1.26.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c21d6ae4fae86ed734cdc1f9e31fe818b074791c7400228f21863f0bceb8df1"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
