name = "The Village 26.2"
author = "CracklyDuck"
version = "1.26.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42b59aadfa20ad65db9bf220e114d2017bcf5daaca673684049785aa5ec01a2d"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
