name = "The Village 26.2"
author = "CracklyDuck"
version = "1.26.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfbff8c8553d172d69acde89036b5fe3f10b1413ad2c478975d5367bf8e84a49"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
