name = "The Village 26.2"
author = "CracklyDuck"
version = "1.26.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25a66085919eee51582cce3152b92d7e226d092f6a1804002400e2b4a50f9475"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
